FROM python:3.12-slim

WORKDIR /app

# Install deps
COPY pyproject.toml uv.lock ./
RUN pip install uv && uv pip install --system -r pyproject.toml

# Copy app code
COPY joker_bot joker_bot
COPY alembic alembic
COPY alembic.ini .

EXPOSE 8000

CMD ["uvicorn", "joker_bot.web.api.app:app", "--host", "0.0.0.0", "--port", "8000"]
