"""update economy models

Revision ID: d74d33a13ff4
Revises: 0410da434d50
Create Date: 2026-01-11 18:05:59.157747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd74d33a13ff4'
down_revision: Union[str, Sequence[str], None] = '0410da434d50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('sender_username', sa.String(), nullable=False))
    op.add_column('transaction', sa.Column('description', sa.String(), nullable=True))
    op.add_column('transaction', sa.Column('receiver_username', sa.String(), nullable=False))
    op.drop_constraint(op.f('transaction_receiver_id_fkey'), 'transaction', type_='foreignkey')
    op.drop_constraint(op.f('transaction_sender_id_fkey'), 'transaction', type_='foreignkey')
    op.create_foreign_key(None, 'transaction', 'user', ['receiver_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'transaction', 'user', ['sender_id'], ['id'], ondelete='SET NULL')
    op.add_column('user', sa.Column('username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'username')
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.create_foreign_key(op.f('transaction_sender_id_fkey'), 'transaction', 'user', ['sender_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('transaction_receiver_id_fkey'), 'transaction', 'user', ['receiver_id'], ['id'], ondelete='CASCADE')
    op.drop_column('transaction', 'receiver_username')
    op.drop_column('transaction', 'description')
    op.drop_column('transaction', 'sender_username')
    # ### end Alembic commands ###
