"""add chat_message

Revision ID: daf239aee2dc
Revises: d74d33a13ff4
Create Date: 2026-01-13 16:51:32.750418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daf239aee2dc'
down_revision: Union[str, Sequence[str], None] = 'd74d33a13ff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_message',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('guild_id', sa.String(), nullable=True),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_message_author_id'), 'chat_message', ['author_id'], unique=False)
    op.create_index(op.f('ix_chat_message_channel_id'), 'chat_message', ['channel_id'], unique=False)
    op.create_index(op.f('ix_chat_message_guild_id'), 'chat_message', ['guild_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_message_guild_id'), table_name='chat_message')
    op.drop_index(op.f('ix_chat_message_channel_id'), table_name='chat_message')
    op.drop_index(op.f('ix_chat_message_author_id'), table_name='chat_message')
    op.drop_table('chat_message')
    # ### end Alembic commands ###
